// src/context/actionTypes.js
export const DECK_ACTIONS = {
  LOAD_DECKS: 'LOAD_DECKS',
  ADD_DECK: 'ADD_DECK',
  UPDATE_DECK: 'UPDATE_DECK',
  DELETE_DECK: 'DELETE_DECK',
  SET_ACTIVE_DECK: 'SET_ACTIVE_DECK'
};

export const CARD_ACTIONS = {
  LOAD_CARDS: 'LOAD_CARDS',
  ADD_CARD: 'ADD_CARD',
  UPDATE_CARD: 'UPDATE_CARD',
  DELETE_CARD: 'DELETE_CARD',
  BULK_DELETE_CARDS: 'BULK_DELETE_CARDS'
};

export const UI_ACTIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
};